create table if not exists users (
    id bigint generated by default as identity primary key,
    email varchar(255) not null,
    name varchar(255) not null,

    constraint uq_users_email unique (email)
);

create table if not exists categories (
    id bigint generated by default as identity primary key,
    name varchar(50) not null,

    constraint uq_categories_name unique (name)
);

create table if not exists compilations (
    id bigint generated by default as identity primary key,
    title varchar(50) not null,
    pinned boolean not null
);

create table if not exists events (
    id bigint generated by default as identity primary key,
    annotation varchar(2000) not null,
    description varchar(7000) not null,
    event_date timestamp not null,
    created_on timestamp not null,
    published_on timestamp,
    title varchar(120) not null,
    paid boolean not null,
    participant_limit integer not null,
    request_moderation boolean not null,
    state varchar(20) not null,
    category_id bigint not null,
    initiator_id bigint not null,
    lat double precision not null,
    lon double precision not null,

    constraint fk_events_category
        foreign key (category_id) references categories (id),

    constraint fk_events_initiator
        foreign key (initiator_id) references users (id)
);

create table if not exists requests (
    id bigint generated by default as identity primary key,
    created timestamp not null,
    event_id bigint not null,
    requester_id bigint not null,
    status varchar(20) not null,

    constraint fk_requests_event
        foreign key (event_id) references events (id),

    constraint fk_requests_requester
        foreign key (requester_id) references users (id),

    constraint uq_requests_event_requester
        unique (event_id, requester_id)
);

create table if not exists compilation_events (
    compilation_id bigint not null,
    event_id bigint not null,

    constraint pk_compilation_events
        primary key (compilation_id, event_id),

    constraint fk_compilation_events_compilation
        foreign key (compilation_id) references compilations (id) on delete cascade,

    constraint fk_compilation_events_event
        foreign key (event_id) references events (id) on delete cascade
);

create table if not exists comments (
    id bigint generated by default as identity primary key,
    text varchar(5000) not null,
    created timestamp not null,
    updated timestamp not null,
    status varchar(20) not null,
    event_id bigint not null,
    author_id bigint not null,

    constraint fk_comments_events
        foreign key (event_id) references events (id) on delete cascade,

    constraint fk_comments_authors
        foreign key (author_id) references users (id) on delete cascade
);

create index if not exists idx_events_category_id on events (category_id);
create index if not exists idx_events_initiator_id on events (initiator_id);
create index if not exists idx_events_event_date on events (event_date);
create index if not exists idx_events_state on events (state);

create index if not exists idx_requests_event_id on requests (event_id);
create index if not exists idx_requests_requester_id on requests (requester_id);

create index if not exists idx_compilation_events_event_id on compilation_events (event_id);

create index if not exists idx_comments_event_id on comments (event_id);
create index if not exists idx_comments_user_id on comments (author_id);
create index if not exists idx_comments_status on comments (status);