drop table if exists hits;

create table if not exists hits (
    id bigint generated by default as identity primary key,
    app varchar(255) not null,
    uri varchar(512) not null,
    ip varchar(45) not null,
    created timestamp without time zone not null
);